// Maps a palette (src/palettes.mjs) onto a complete VS Code color theme.
// Both variants go through this same template so they never drift apart.

/** Appends a two-digit hex alpha to a #RRGGBB color. */
const a = (hex, alpha) => `${hex}${alpha}`;

function workbenchColors(p) {
  const { chrome, bg, border, fg, accent, selection: sel, status, git, syntax, ansi } = p;
  const isDark = p.type === 'dark';
  const shadow = isDark ? '#00000080' : '#00000026';
  const selection = sel.editor;
  const listSelection = sel.list;

  return {
    // Base
    foreground: fg.main,
    descriptionForeground: fg.muted,
    disabledForeground: fg.dim,
    errorForeground: status.error,
    focusBorder: a(accent.main, 'B3'),
    'icon.foreground': fg.muted,
    'selection.background': a(accent.main, '4D'),
    'widget.shadow': shadow,
    'widget.border': border.subtle,
    'sash.hoverBorder': accent.main,
    'textLink.foreground': accent.text,
    'textLink.activeForeground': accent.main,
    'textBlockQuote.background': bg.widget,
    'textBlockQuote.border': accent.main,
    'textCodeBlock.background': bg.widget,
    'textPreformat.foreground': syntax.string,
    'textPreformat.background': a(fg.main, '0F'),
    'textSeparator.foreground': border.strong,
    'toolbar.hoverBackground': a(fg.main, '14'),
    'toolbar.activeBackground': a(fg.main, '1F'),

    // Buttons
    'button.background': accent.deep,
    'button.foreground': fg.onAccent,
    'button.hoverBackground': accent.hover,
    'button.separator': a(fg.onAccent, '66'),
    'button.secondaryBackground': bg.active,
    'button.secondaryForeground': fg.main,
    'button.secondaryHoverBackground': border.strong,
    'checkbox.background': bg.input,
    'checkbox.border': border.strong,
    'checkbox.foreground': fg.main,

    // Dropdowns and inputs
    'dropdown.background': bg.input,
    'dropdown.listBackground': bg.widget,
    'dropdown.border': border.strong,
    'dropdown.foreground': fg.main,
    'input.background': bg.input,
    'input.border': border.strong,
    'input.foreground': fg.main,
    'input.placeholderForeground': fg.dim,
    'inputOption.activeBackground': a(accent.main, '33'),
    'inputOption.activeBorder': accent.main,
    'inputOption.activeForeground': fg.main,
    'inputOption.hoverBackground': a(fg.main, '14'),
    'inputValidation.errorBackground': bg.widget,
    'inputValidation.errorBorder': status.error,
    'inputValidation.errorForeground': fg.main,
    'inputValidation.warningBackground': bg.widget,
    'inputValidation.warningBorder': status.warning,
    'inputValidation.warningForeground': fg.main,
    'inputValidation.infoBackground': bg.widget,
    'inputValidation.infoBorder': status.info,
    'inputValidation.infoForeground': fg.main,

    // Scrollbars, badges, progress
    'scrollbar.shadow': isDark ? '#00000066' : '#0000001A',
    'scrollbarSlider.background': a(fg.muted, '26'),
    'scrollbarSlider.hoverBackground': a(fg.muted, '40'),
    'scrollbarSlider.activeBackground': a(accent.main, '66'),
    'badge.background': accent.deep,
    'badge.foreground': fg.onAccent,
    'progressBar.background': accent.main,

    // Lists and trees
    'list.activeSelectionBackground': listSelection,
    'list.activeSelectionForeground': fg.main,
    'list.activeSelectionIconForeground': fg.main,
    'list.inactiveSelectionBackground': bg.active,
    'list.inactiveSelectionForeground': fg.main,
    'list.hoverBackground': bg.hover,
    'list.hoverForeground': fg.main,
    'list.focusOutline': a(accent.main, '99'),
    'list.inactiveFocusOutline': border.strong,
    'list.focusAndSelectionOutline': a(accent.main, '99'),
    'list.highlightForeground': accent.text,
    'list.focusHighlightForeground': accent.text,
    'list.dropBackground': a(accent.main, '26'),
    'list.errorForeground': status.error,
    'list.warningForeground': status.warning,
    'list.invalidItemForeground': status.error,
    'list.deemphasizedForeground': fg.dim,
    'listFilterWidget.background': bg.widget,
    'listFilterWidget.outline': accent.main,
    'listFilterWidget.noMatchesOutline': status.error,
    'tree.indentGuidesStroke': border.strong,
    'tree.inactiveIndentGuidesStroke': border.subtle,

    // Activity bar
    'activityBar.background': chrome.activity,
    'activityBar.foreground': chrome.activityFg,
    'activityBar.inactiveForeground': chrome.activityDim,
    'activityBar.border': border.subtle,
    'activityBar.activeBorder': chrome.activityActive,
    'activityBar.activeBackground': a(chrome.activityActive, '14'),
    'activityBar.activeFocusBorder': chrome.activityActive,
    'activityBarBadge.background': chrome.badge,
    'activityBarBadge.foreground': chrome.badgeFg,
    'activityBarTop.foreground': fg.main,
    'activityBarTop.inactiveForeground': fg.dim,
    'activityBarTop.activeBorder': accent.main,

    // Side bar
    'sideBar.background': bg.side,
    'sideBar.foreground': fg.main,
    'sideBar.border': border.subtle,
    'sideBar.dropBackground': a(accent.main, '1F'),
    'sideBarTitle.foreground': fg.muted,
    'sideBarSectionHeader.background': bg.side,
    'sideBarSectionHeader.foreground': fg.main,
    'sideBarSectionHeader.border': border.subtle,
    'sideBarActivityBarTop.border': border.subtle,
    'sideBarStickyScroll.background': bg.side,
    'sideBarStickyScroll.shadow': shadow,

    // Minimap
    'minimap.background': bg.editor,
    'minimap.selectionHighlight': a(accent.main, '80'),
    'minimap.findMatchHighlight': a(status.warning, '99'),
    'minimap.errorHighlight': a(status.error, 'B3'),
    'minimap.warningHighlight': a(status.warning, 'B3'),
    'minimapSlider.background': a(fg.muted, '1A'),
    'minimapSlider.hoverBackground': a(fg.muted, '26'),
    'minimapSlider.activeBackground': a(fg.muted, '33'),
    'minimapGutter.addedBackground': git.added,
    'minimapGutter.modifiedBackground': git.modified,
    'minimapGutter.deletedBackground': git.deleted,

    // Editor groups and tabs
    'editorGroup.border': border.subtle,
    'editorGroup.dropBackground': a(accent.main, '1F'),
    'editorGroup.emptyBackground': bg.editor,
    'editorGroupHeader.tabsBackground': bg.side,
    'editorGroupHeader.tabsBorder': border.subtle,
    'editorGroupHeader.noTabsBackground': bg.editor,
    'tab.activeBackground': bg.editor,
    'tab.activeForeground': fg.main,
    'tab.activeBorderTop': accent.main,
    'tab.activeBorder': bg.editor,
    'tab.inactiveBackground': bg.side,
    'tab.inactiveForeground': fg.muted,
    'tab.border': border.subtle,
    'tab.hoverBackground': bg.hover,
    'tab.hoverForeground': fg.main,
    'tab.unfocusedActiveForeground': fg.muted,
    'tab.unfocusedActiveBorderTop': a(accent.main, '66'),
    'tab.unfocusedInactiveForeground': fg.dim,
    'tab.unfocusedHoverBackground': bg.hover,
    'tab.activeModifiedBorder': accent.sheen,
    'tab.inactiveModifiedBorder': a(accent.sheen, '80'),
    'tab.lastPinnedBorder': border.strong,
    'tab.selectedBackground': bg.editor,
    'tab.selectedForeground': fg.main,
    'tab.selectedBorderTop': accent.sheen,

    // Breadcrumbs
    'breadcrumb.background': bg.editor,
    'breadcrumb.foreground': fg.muted,
    'breadcrumb.focusForeground': fg.main,
    'breadcrumb.activeSelectionForeground': accent.text,
    'breadcrumbPicker.background': bg.widget,

    // Editor
    'editor.background': bg.editor,
    'editor.foreground': fg.main,
    'editorLineNumber.foreground': fg.dim,
    'editorLineNumber.activeForeground': accent.text,
    'editorLineNumber.dimmedForeground': a(fg.dim, '80'),
    'editorCursor.foreground': accent.main,
    'editorCursor.background': bg.editor,
    'editor.selectionBackground': selection,
    'editor.inactiveSelectionBackground': sel.inactive,
    'editor.selectionHighlightBackground': sel.highlight,
    'editor.wordHighlightBackground': a(syntax.type, '26'),
    'editor.wordHighlightStrongBackground': a(accent.main, '26'),
    'editor.wordHighlightTextBackground': a(fg.muted, '1F'),
    'editor.findMatchBackground': sel.find,
    'editor.findMatchBorder': sel.findBorder,
    'editor.findMatchHighlightBackground': sel.findHighlight,
    'editor.findRangeHighlightBackground': a(fg.muted, '14'),
    'editor.hoverHighlightBackground': a(syntax.type, '1F'),
    'editor.lineHighlightBackground': a(fg.main, '0A'),
    'editor.lineHighlightBorder': '#00000000',
    'editor.rangeHighlightBackground': a(accent.main, '14'),
    'editor.symbolHighlightBackground': a(accent.main, '26'),
    'editor.linkedEditingBackground': a(accent.main, '1A'),
    'editor.foldBackground': a(accent.main, '0F'),
    'editor.stackFrameHighlightBackground': a(status.warning, '26'),
    'editor.focusedStackFrameHighlightBackground': a(status.success, '26'),
    'editorWhitespace.foreground': fg.faint,
    'editorIndentGuide.background1': fg.faint,
    'editorIndentGuide.activeBackground1': a(accent.main, '80'),
    'editorRuler.foreground': border.subtle,
    'editorCodeLens.foreground': fg.dim,
    'editorLink.activeForeground': accent.text,
    'editorGhostText.foreground': fg.dim,
    'editorLightBulb.foreground': status.warning,
    'editorLightBulbAutoFix.foreground': accent.main,
    'editorInlayHint.foreground': fg.muted,
    'editorInlayHint.background': a(fg.muted, '14'),
    'editorStickyScroll.background': bg.editor,
    'editorStickyScroll.shadow': shadow,
    'editorStickyScrollHover.background': bg.hover,

    // Brackets
    'editorBracketMatch.background': a(accent.main, '1F'),
    'editorBracketMatch.border': a(accent.main, '99'),
    ...Object.fromEntries(
      p.brackets.flatMap((color, i) => [
        [`editorBracketHighlight.foreground${i + 1}`, color],
        [`editorBracketPairGuide.activeBackground${i + 1}`, a(color, '80')],
      ]),
    ),
    'editorBracketHighlight.unexpectedBracket.foreground': status.error,

    // Diagnostics and gutter
    'editorError.foreground': status.error,
    'editorWarning.foreground': status.warning,
    'editorInfo.foreground': status.info,
    'editorHint.foreground': status.success,
    'editorGutter.background': bg.editor,
    'editorGutter.addedBackground': git.added,
    'editorGutter.modifiedBackground': git.modified,
    'editorGutter.deletedBackground': git.deleted,
    'editorGutter.foldingControlForeground': fg.muted,
    'editorOverviewRuler.border': border.subtle,
    'editorOverviewRuler.findMatchForeground': a(status.warning, 'B3'),
    'editorOverviewRuler.selectionHighlightForeground': a(accent.main, '99'),
    'editorOverviewRuler.wordHighlightForeground': a(syntax.type, '99'),
    'editorOverviewRuler.bracketMatchForeground': accent.main,
    'editorOverviewRuler.addedForeground': git.added,
    'editorOverviewRuler.modifiedForeground': git.modified,
    'editorOverviewRuler.deletedForeground': git.deleted,
    'editorOverviewRuler.errorForeground': status.error,
    'editorOverviewRuler.warningForeground': status.warning,
    'editorOverviewRuler.infoForeground': status.info,
    'editorMarkerNavigation.background': bg.widget,
    'editorMarkerNavigationError.background': status.error,
    'editorMarkerNavigationWarning.background': status.warning,
    'editorMarkerNavigationInfo.background': status.info,

    // Editor widgets
    'editorWidget.background': bg.widget,
    'editorWidget.foreground': fg.main,
    'editorWidget.border': border.strong,
    'editorWidget.resizeBorder': accent.main,
    'editorSuggestWidget.background': bg.widget,
    'editorSuggestWidget.border': border.strong,
    'editorSuggestWidget.foreground': fg.main,
    'editorSuggestWidget.highlightForeground': accent.text,
    'editorSuggestWidget.focusHighlightForeground': accent.text,
    'editorSuggestWidget.selectedBackground': listSelection,
    'editorSuggestWidget.selectedForeground': fg.main,
    'editorSuggestWidget.selectedIconForeground': fg.main,
    'editorHoverWidget.background': bg.widget,
    'editorHoverWidget.border': border.strong,
    'editorHoverWidget.foreground': fg.main,
    'editorHoverWidget.highlightForeground': accent.text,
    'editorHoverWidget.statusBarBackground': bg.hover,
    'editorActionList.background': bg.widget,
    'editorActionList.foreground': fg.main,
    'editorActionList.focusBackground': listSelection,
    'editorActionList.focusForeground': fg.main,
    'debugExceptionWidget.background': bg.widget,
    'debugExceptionWidget.border': status.error,

    // Peek view
    'peekView.border': accent.main,
    'peekViewEditor.background': bg.side,
    'peekViewEditorGutter.background': bg.side,
    'peekViewEditor.matchHighlightBackground': sel.find,
    'peekViewResult.background': bg.deep,
    'peekViewResult.fileForeground': fg.main,
    'peekViewResult.lineForeground': fg.muted,
    'peekViewResult.matchHighlightBackground': sel.find,
    'peekViewResult.selectionBackground': listSelection,
    'peekViewResult.selectionForeground': fg.main,
    'peekViewTitle.background': bg.widget,
    'peekViewTitleLabel.foreground': fg.main,
    'peekViewTitleDescription.foreground': fg.muted,

    // Diff and merge
    'diffEditor.insertedTextBackground': a(git.added, isDark ? '26' : '2E'),
    'diffEditor.removedTextBackground': a(git.deleted, '26'),
    'diffEditor.insertedLineBackground': a(git.added, '14'),
    'diffEditor.removedLineBackground': a(git.deleted, '14'),
    'diffEditor.border': border.subtle,
    'diffEditor.diagonalFill': a(fg.dim, '33'),
    'merge.currentHeaderBackground': a(git.added, '4D'),
    'merge.currentContentBackground': a(git.added, '1A'),
    'merge.incomingHeaderBackground': a(syntax.type, '4D'),
    'merge.incomingContentBackground': a(syntax.type, '1A'),
    'merge.commonHeaderBackground': a(fg.dim, '4D'),
    'merge.commonContentBackground': a(fg.dim, '1A'),

    // Panel and terminal
    'panel.background': bg.side,
    'panel.border': border.subtle,
    'panelTitle.activeBorder': accent.main,
    'panelTitle.activeForeground': fg.main,
    'panelTitle.inactiveForeground': fg.muted,
    'panelInput.border': border.strong,
    'panelSection.border': border.subtle,
    'panelSectionHeader.background': bg.side,
    'terminal.background': bg.side,
    'terminal.foreground': fg.main,
    'terminal.border': border.subtle,
    'terminal.selectionBackground': selection,
    'terminal.findMatchBackground': sel.find,
    'terminal.findMatchHighlightBackground': sel.findHighlight,
    'terminal.tab.activeBorder': accent.main,
    'terminalCursor.foreground': accent.main,
    'terminalCommandDecoration.defaultBackground': fg.dim,
    'terminalCommandDecoration.successBackground': status.success,
    'terminalCommandDecoration.errorBackground': status.error,
    ...Object.fromEntries(
      Object.entries(ansi).map(([name, color]) => [
        `terminal.ansi${name[0].toUpperCase()}${name.slice(1)}`,
        color,
      ]),
    ),

    // Status bar
    'statusBar.background': chrome.status,
    'statusBar.foreground': chrome.statusFg,
    'statusBar.border': chrome.statusBorder,
    'statusBar.focusBorder': chrome.statusFg,
    'statusBar.debuggingBackground': chrome.statusDebug,
    'statusBar.debuggingForeground': chrome.statusDebugFg,
    'statusBar.debuggingBorder': chrome.statusDebug,
    'statusBar.noFolderBackground': chrome.status,
    'statusBar.noFolderForeground': chrome.statusFg,
    'statusBar.noFolderBorder': chrome.statusBorder,
    'statusBarItem.hoverBackground': chrome.statusHover,
    'statusBarItem.hoverForeground': chrome.statusFg,
    'statusBarItem.activeBackground': chrome.statusHover,
    'statusBarItem.remoteBackground': chrome.remote,
    'statusBarItem.remoteForeground': chrome.remoteFg,
    'statusBarItem.remoteHoverBackground': a(chrome.remote, 'CC'),
    'statusBarItem.remoteHoverForeground': chrome.remoteFg,
    'statusBarItem.prominentBackground': chrome.statusHover,
    'statusBarItem.prominentForeground': chrome.statusFg,
    'statusBarItem.prominentHoverBackground': chrome.statusHover,
    'statusBarItem.errorBackground': status.error,
    'statusBarItem.errorForeground': fg.onAccent,
    'statusBarItem.warningBackground': status.warning,
    'statusBarItem.warningForeground': fg.onAccent,

    // Title bar and command center
    'titleBar.activeBackground': chrome.title,
    'titleBar.activeForeground': chrome.titleFg,
    'titleBar.inactiveBackground': chrome.title,
    'titleBar.inactiveForeground': chrome.titleInactiveFg,
    'titleBar.border': border.subtle,
    'commandCenter.background': chrome.commandCenter,
    'commandCenter.foreground': chrome.commandCenterFg,
    'commandCenter.activeBackground': a(chrome.titleFg, '1A'),
    'commandCenter.activeForeground': chrome.titleFg,
    'commandCenter.border': chrome.commandCenterBorder,
    'commandCenter.activeBorder': a(chrome.titleFg, '80'),
    'commandCenter.inactiveForeground': chrome.titleInactiveFg,
    'commandCenter.inactiveBorder': chrome.commandCenterBorder,

    // Menus, quick input, keybindings
    'menu.background': bg.widget,
    'menu.foreground': fg.main,
    'menu.border': border.strong,
    'menu.selectionBackground': listSelection,
    'menu.selectionForeground': fg.main,
    'menu.separatorBackground': border.strong,
    'menubar.selectionBackground': a(chrome.titleFg, '1F'),
    'menubar.selectionForeground': chrome.titleFg,
    'quickInput.background': bg.widget,
    'quickInput.foreground': fg.main,
    'quickInputTitle.background': bg.hover,
    'quickInputList.focusBackground': listSelection,
    'quickInputList.focusForeground': fg.main,
    'quickInputList.focusIconForeground': fg.main,
    'pickerGroup.border': border.strong,
    'pickerGroup.foreground': accent.text,
    'keybindingLabel.background': a(fg.muted, '1A'),
    'keybindingLabel.foreground': fg.main,
    'keybindingLabel.border': border.strong,
    'keybindingLabel.bottomBorder': border.strong,

    // Notifications and banner
    'notificationCenter.border': border.strong,
    'notificationCenterHeader.background': bg.hover,
    'notificationCenterHeader.foreground': fg.main,
    'notifications.background': bg.widget,
    'notifications.foreground': fg.main,
    'notifications.border': border.subtle,
    'notificationToast.border': border.strong,
    'notificationLink.foreground': accent.text,
    'notificationsErrorIcon.foreground': status.error,
    'notificationsWarningIcon.foreground': status.warning,
    'notificationsInfoIcon.foreground': status.info,
    'banner.background': accent.deep,
    'banner.foreground': fg.onAccent,
    'banner.iconForeground': fg.onAccent,

    // Extensions
    'extensionButton.background': accent.deep,
    'extensionButton.foreground': fg.onAccent,
    'extensionButton.hoverBackground': accent.hover,
    'extensionButton.prominentBackground': accent.deep,
    'extensionButton.prominentForeground': fg.onAccent,
    'extensionButton.prominentHoverBackground': accent.hover,
    'extensionBadge.remoteBackground': accent.deep,
    'extensionBadge.remoteForeground': fg.onAccent,
    'extensionIcon.starForeground': status.warning,

    // Source control
    'gitDecoration.addedResourceForeground': git.added,
    'gitDecoration.modifiedResourceForeground': git.modified,
    'gitDecoration.deletedResourceForeground': git.deleted,
    'gitDecoration.renamedResourceForeground': git.added,
    'gitDecoration.untrackedResourceForeground': git.untracked,
    'gitDecoration.ignoredResourceForeground': git.ignored,
    'gitDecoration.conflictingResourceForeground': git.conflict,
    'gitDecoration.submoduleResourceForeground': git.submodule,
    'gitDecoration.stageModifiedResourceForeground': git.modified,
    'gitDecoration.stageDeletedResourceForeground': git.deleted,

    // Debug
    'debugToolBar.background': bg.widget,
    'debugToolBar.border': border.strong,
    'debugIcon.breakpointForeground': status.error,
    'debugIcon.startForeground': status.success,
    'debugIcon.pauseForeground': status.info,
    'debugIcon.stopForeground': status.error,
    'debugIcon.restartForeground': status.success,
    'debugIcon.continueForeground': status.info,
    'debugTokenExpression.name': syntax.property,
    'debugTokenExpression.value': fg.main,
    'debugTokenExpression.string': syntax.string,
    'debugTokenExpression.number': syntax.number,
    'debugTokenExpression.boolean': syntax.constant,
    'debugTokenExpression.error': status.error,
    'debugConsole.infoForeground': status.info,
    'debugConsole.warningForeground': status.warning,
    'debugConsole.errorForeground': status.error,
    'debugConsole.sourceForeground': fg.muted,

    // Search
    'search.resultsInfoForeground': fg.muted,
    'searchEditor.findMatchBackground': sel.find,

    // Settings editor
    'settings.headerForeground': fg.main,
    'settings.headerBorder': border.subtle,
    'settings.sashBorder': border.subtle,
    'settings.modifiedItemIndicator': accent.main,
    'settings.focusedRowBackground': a(fg.main, '08'),
    'settings.rowHoverBackground': a(fg.main, '05'),
    'settings.focusedRowBorder': a(accent.main, '66'),
    'settings.dropdownBackground': bg.input,
    'settings.dropdownBorder': border.strong,
    'settings.textInputBackground': bg.input,
    'settings.textInputBorder': border.strong,
    'settings.numberInputBackground': bg.input,
    'settings.numberInputBorder': border.strong,
    'settings.checkboxBackground': bg.input,
    'settings.checkboxBorder': border.strong,

    // Notebooks
    'notebook.cellBorderColor': border.subtle,
    'notebook.focusedCellBorder': a(accent.main, '99'),
    'notebook.selectedCellBackground': a(fg.main, '08'),
    'notebook.cellEditorBackground': bg.side,
    'notebook.outputContainerBackgroundColor': bg.side,
    'notebookStatusSuccessIcon.foreground': status.success,
    'notebookStatusErrorIcon.foreground': status.error,
    'notebookStatusRunningIcon.foreground': status.info,

    // Welcome page and walkthroughs
    'welcomePage.tileBackground': bg.widget,
    'welcomePage.tileHoverBackground': bg.hover,
    'welcomePage.tileBorder': border.subtle,
    'welcomePage.progress.background': border.strong,
    'welcomePage.progress.foreground': accent.main,
    'walkThrough.embeddedEditorBackground': bg.side,

    // Charts
    'charts.foreground': fg.main,
    'charts.lines': fg.dim,
    'charts.red': status.error,
    'charts.blue': syntax.type,
    'charts.yellow': status.warning,
    'charts.orange': accent.main,
    'charts.green': status.success,
    'charts.purple': ansi.magenta,
  };
}

function tokenColors(p) {
  const { syntax: s, status } = p;
  const rule = (name, scope, foreground, fontStyle) => ({
    name,
    scope,
    settings: fontStyle === undefined ? { foreground } : { foreground, fontStyle },
  });

  return [
    rule('Comments', ['comment', 'punctuation.definition.comment', 'string.comment'], s.comment, 'italic'),
    rule('Doc comment tags', ['storage.type.class.jsdoc', 'punctuation.definition.block.tag.jsdoc', 'keyword.other.phpdoc'], s.keyword, 'italic'),
    rule('Doc comment types and names', ['comment.block.documentation entity.name.type', 'comment.block.documentation variable'], s.type, 'italic'),

    rule('Strings', ['string', 'string.quoted', 'string.template', 'punctuation.definition.string'], s.string),
    rule('Template expressions', ['punctuation.definition.template-expression', 'punctuation.section.embedded'], s.keyword),
    rule('Template expression body', ['meta.template.expression', 'meta.embedded.line'], s.variable),
    rule('Regular expressions', ['string.regexp', 'string.regexp punctuation.definition.string'], s.regexp),
    rule('Escapes and placeholders', ['constant.character.escape', 'constant.character.format.placeholder', 'constant.other.placeholder'], s.escape),

    rule('Numbers and units', ['constant.numeric', 'keyword.other.unit', 'constant.other.color.rgb-value', 'constant.other.rgb-value'], s.number),
    rule('Language constants', ['constant.language', 'support.constant', 'constant.other.caps', 'constant.character', 'constant.other.symbol', 'variable.other.enummember', 'support.variable.magic'], s.constant),

    rule('Keywords and storage', ['keyword', 'keyword.control', 'keyword.other', 'storage.type', 'storage.modifier'], s.keyword),
    rule('Operators', ['keyword.operator'], s.operator),
    rule('Word operators', [
      'keyword.operator.new',
      'keyword.operator.expression',
      'keyword.operator.logical.python',
      'keyword.operator.word',
      'keyword.operator.delete',
      'keyword.operator.sizeof',
      'keyword.operator.instanceof',
      'keyword.operator.typeof',
      'keyword.operator.cast',
    ], s.keyword),
    rule('Language variables (this, self, super)', ['variable.language', 'variable.parameter.function.language.special.self', 'variable.parameter.function.language.special.cls'], s.keyword, 'italic'),

    rule('Variables', ['variable', 'variable.other.readwrite', 'meta.definition.variable', 'variable.other.object'], s.variable),
    rule('Parameters', ['variable.parameter', 'meta.parameter', 'entity.name.variable.parameter'], s.parameter, 'italic'),
    rule('Properties and keys', [
      'variable.other.property',
      'variable.other.object.property',
      'variable.other.member',
      'support.variable.property',
      'meta.object-literal.key',
      'entity.name.variable.field',
      'support.type.property-name',
      'punctuation.support.type.property-name',
      'entity.name.tag.yaml',
    ], s.property),

    rule('Functions', [
      'entity.name.function',
      'support.function',
      'variable.function',
      'meta.function-call.generic',
      'support.function.magic',
      'support.function.builtin.shell',
    ], s.func),
    rule('Decorators, annotations and macros', [
      'meta.decorator',
      'entity.name.function.decorator',
      'punctuation.definition.decorator',
      'storage.type.annotation',
      'meta.attribute.rust',
      'entity.name.function.macro',
      'support.function.macro',
    ], s.decorator),

    rule('Types and classes', [
      'entity.name.type',
      'entity.name.class',
      'entity.name.struct',
      'entity.name.trait',
      'entity.other.inherited-class',
      'support.type',
      'support.class',
      'support.class.component',
      'storage.type.primitive',
      'storage.type.built-in',
      'storage.type.numeric',
      'storage.type.boolean',
      'storage.type.byte',
      'storage.type.java',
      'storage.type.cs',
    ], s.type),
    rule('Namespaces and modules', [
      'entity.name.namespace',
      'entity.name.module',
      'entity.name.type.module',
      'entity.name.package',
      'support.module',
      'storage.modifier.import.java',
      'storage.modifier.package.java',
    ], s.namespace),

    rule('Tags', ['entity.name.tag', 'meta.tag.sgml'], s.tag),
    rule('Attributes', ['entity.other.attribute-name'], s.attribute, 'italic'),
    rule('CSS class and pseudo selectors', ['entity.other.attribute-name.class', 'entity.other.attribute-name.pseudo-class', 'entity.other.attribute-name.pseudo-element'], s.func, ''),
    rule('CSS id selectors', ['entity.other.attribute-name.id'], s.constant, ''),
    rule('CSS at-rules', ['keyword.control.at-rule', 'punctuation.definition.keyword.css'], s.keyword),
    rule('CSS property values', ['support.constant.property-value', 'support.constant.font-name', 'support.constant.color'], s.constant),

    rule('Punctuation', [
      'punctuation',
      'meta.brace',
      'punctuation.separator',
      'punctuation.terminator',
      'punctuation.accessor',
      'punctuation.definition.tag',
      'meta.delimiter',
    ], s.punctuation),

    rule('Markup headings', ['markup.heading', 'entity.name.section.markdown', 'punctuation.definition.heading.markdown', 'markup.heading.setext'], s.heading, 'bold'),
    rule('Markup bold', ['markup.bold'], s.func, 'bold'),
    rule('Markup italic', ['markup.italic'], s.parameter, 'italic'),
    rule('Markup strikethrough', ['markup.strikethrough'], s.comment, 'strikethrough'),
    rule('Markup inline code', ['markup.inline.raw', 'markup.raw', 'markup.fenced_code.block'], s.string),
    rule('Markup links', ['markup.underline.link', 'string.other.link.description', 'constant.other.reference.link'], s.link, 'underline'),
    rule('Markup link text', ['string.other.link.title', 'markup.link'], s.property),
    rule('Markup quotes', ['markup.quote'], s.comment, 'italic'),
    rule('Markup lists', ['punctuation.definition.list.begin.markdown', 'beginning.punctuation.definition.list.markdown', 'beginning.punctuation.definition.quote.markdown'], s.keyword),
    rule('Markup separators', ['meta.separator.markdown'], s.comment),

    rule('Diff inserted', ['markup.inserted', 'meta.diff.header.to-file', 'punctuation.definition.inserted'], s.inserted),
    rule('Diff deleted', ['markup.deleted', 'meta.diff.header.from-file', 'punctuation.definition.deleted'], s.deleted),
    rule('Diff changed', ['markup.changed', 'punctuation.definition.changed'], s.type),
    rule('Diff range', ['meta.diff.range', 'meta.diff.header'], s.keyword),

    rule('Invalid', ['invalid', 'invalid.illegal'], s.invalid),
    rule('Deprecated', ['invalid.deprecated'], status.warning, 'strikethrough'),
  ];
}

function semanticTokenColors(p) {
  const s = p.syntax;
  return {
    namespace: s.namespace,
    class: s.type,
    'class.defaultLibrary': s.type,
    interface: s.type,
    struct: s.type,
    enum: s.type,
    type: s.type,
    'type.defaultLibrary': s.type,
    typeParameter: { foreground: s.type, italic: true },
    enumMember: s.constant,
    function: s.func,
    method: s.func,
    macro: s.decorator,
    decorator: s.decorator,
    parameter: { foreground: s.parameter, italic: true },
    selfParameter: { foreground: s.keyword, italic: true },
    clsParameter: { foreground: s.keyword, italic: true },
    property: s.property,
    variable: s.variable,
    'variable.defaultLibrary': s.type,
    keyword: s.keyword,
    '*.deprecated': { strikethrough: true },
  };
}

export function buildTheme(p) {
  return {
    $schema: 'vscode://schemas/color-theme',
    name: p.name,
    type: p.type,
    semanticHighlighting: true,
    colors: workbenchColors(p),
    tokenColors: tokenColors(p),
    semanticTokenColors: semanticTokenColors(p),
  };
}
